#include <libavutil/error.h>
#include <stdio.h>

#define PRINTERROR(E) { printf("%s: %d\n", #E, E); }

int main (void) {
  PRINTERROR(AVERROR(EINVAL));
  PRINTERROR(AVERROR_BSF_NOT_FOUND      );
  PRINTERROR(AVERROR_BUG                );
  PRINTERROR(AVERROR_BUFFER_TOO_SMALL   );
  PRINTERROR(AVERROR_DECODER_NOT_FOUND  );
  PRINTERROR(AVERROR_DEMUXER_NOT_FOUND  );
  PRINTERROR(AVERROR_ENCODER_NOT_FOUND  );
  PRINTERROR(AVERROR_EOF                );
  PRINTERROR(AVERROR_EXIT               );
  PRINTERROR(AVERROR_EXTERNAL           );
  PRINTERROR(AVERROR_FILTER_NOT_FOUND   );
  PRINTERROR(AVERROR_INVALIDDATA        );
  PRINTERROR(AVERROR_MUXER_NOT_FOUND    );
  PRINTERROR(AVERROR_OPTION_NOT_FOUND   );
  PRINTERROR(AVERROR_PATCHWELCOME       );
  PRINTERROR(AVERROR_PROTOCOL_NOT_FOUND );
 
  PRINTERROR(AVERROR_UNKNOWN            );
  PRINTERROR(AVERROR_EXPERIMENTAL       );
  PRINTERROR(AVERROR_INPUT_CHANGED      );
  PRINTERROR(AVERROR_OUTPUT_CHANGED     );
  PRINTERROR(AVERROR_HTTP_BAD_REQUEST   );
  PRINTERROR(AVERROR_HTTP_UNAUTHORIZED  );
  PRINTERROR(AVERROR_HTTP_FORBIDDEN     );
  PRINTERROR(AVERROR_HTTP_NOT_FOUND     );
  PRINTERROR(AVERROR_HTTP_OTHER_4XX     );
  PRINTERROR(AVERROR_HTTP_SERVER_ERROR  );
}

